site_name: Siber GÃ¼venliÄŸe GiriÅŸ Kursu NotlarÄ±
site_url: https://AhmetEkiz.github.io/SiberGuvenlikGiris/
repo_url: https://github.com/AhmetEkiz/SiberGuvenlikGiris
repo_name: AhmetEkiz/SiberGuvenlikGiris

theme:
  name: material
  language: tr
  user_color_mode_toggle: true
  palette:
    - scheme: default
      primary: red
      accent: amber
      toggle:
        icon: material/weather-night
        name: switch to dark mode
    - scheme: slate
      primary: darkblue
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: switch to light mode

nav:
  - GiriÅŸ: index.md
  - 3 - Linux Temelleri ğŸ§:
      - 3.1. Linux Komutlar: Hafta03-Linux_Temelleri/03_01_Linux_Komutlar.md
      - 3.2. Linux Dosya ve KullanÄ±cÄ± Sistemi: Hafta03-Linux_Temelleri/03_02_Linux_Dosya_ve_KullanÄ±cÄ±_Sistemi.md
  - 4 - Bash Scripting âœğŸ¼:
      - 4.2. Bash Scripting: Hafta04-bash_scripting/04_02_Bash Scripting.md
  - 5 - Pentesting ğŸ•µğŸ¼:
      - 5.1. Etik Hacker Metodolojisi: Hafta05-pentesting/05_01_Etik_Hacker_Metodolojisi.md
      - 5.2. Zafiyetli Makine Kurulumu: Hafta05-pentesting/05_02_Zafiyetli_Makine_Kurulumu.md
      - 5.3. AÄŸ Tarama: Hafta05-pentesting/05_03_AgTarama.md
      - 5.4. SonuÃ§larÄ± Ä°ncelemek: Hafta05-pentesting/05_04_Sonuclari_Incelemek.md
      - 5.5. Ä°lk Hack ve EriÅŸim SaÄŸlamak: Hafta05-pentesting/05_05_Ilk_Hack_ve_Erisim_Saglamak.md
  - 6 - Web GÃ¼venliÄŸi ğŸŒ:
      - 6.1. Web GÃ¼venliÄŸine GiriÅŸ: Hafta06-WebGuvenligi/06_01_WebGuvenligineGiris.md
      - 6.2. Web Pentest AraÃ§larÄ± TanÄ±tÄ±mÄ±: Hafta06-WebGuvenligi/06_02_WebPentestAraclariTanitimi.md
      - 6.3. Burp Suite Nedir?: Hafta06-WebGuvenligi/06_03_BurpSuiteNedir.md
      - 6.3.1. Proxy Nedir?: Hafta06-WebGuvenligi/06_03_01_ProxyNedir.md
      - 6.4. Burp Suite Lab UygulamalarÄ±: Hafta06-WebGuvenligi/06_04_BurpSuiteLabUygulamalari.md

    
